In [9]:
import random
import numpy as np

print("Part A. The sampling probabilities")
print("P(C|-s,r) = <.878, .122>")
print("P(C|-s,-r) = <.310, .690>")
print("P(R|c,-s,w) = <.914, .086>")
print("P(R|-c,-s,w) = <.818, .182>")
print()
print("Part B. The transition probability matrix")
m = np.array([
    [0.9322, 0.0068, 0.0610, 0.0],
    [0.4931, 0.1620, 0.0, 0.3448],
    [0.4390, 0.0, 0.4701, 0.0909],
    [0.0, 0.1551, 0.4091, 0.4357]
])
print(m)
print()
print("Part C. The probability for the query")

N = 1000000 

s1 = 0
s2 = 1
s3 = 2
s4 = 3

cur = random.choice([s1,s2,s3,s4])

countfirst = 0
countsecond = 0

for i in range(N):
    next = random.random()
    if next<m[cur][0]:
        cur = s1
    elif next <m[cur][0] + m[cur][1]:
        cur = s2
    elif next < m[cur][0] + m[cur][1] + m[cur][2]:
        cur = s3
    else:
        cur = s4

    if cur in [s1,s2]:
        countfirst+=1
    else:
        countsecond+=1

alpha = countfirst/N
beta = countsecond/N

print("P(C|-s,w) = <",alpha,",",beta,">")


Part A. The sampling probabilities
P(C|-s,r) = <.878, .122>
P(C|-s,-r) = <.310, .690>
P(R|c,-s,w) = <.914, .086>
P(R|-c,-s,w) = <.818, .182>

Part B. The transition probability matrix
[[0.9322 0.0068 0.061  0.    ]
 [0.4931 0.162  0.     0.3448]
 [0.439  0.     0.4701 0.0909]
 [0.     0.1551 0.4091 0.4357]]

Part C. The probability for the query
P(C|-s,w) = < 0.856482 , 0.143518 >
